#!/bin/bash
# Quick Transfer Script — Send OpenClaw Migration to Brax
# Run this to package and prepare for transfer

set -e

MIGRATION_DIR="/Users/Jakin/.openclaw/workspace/brax-migration"
ARCHIVE="/Users/Jakin/.openclaw/workspace/brax-openclaw-migration.tar.gz"

echo "🦾 OpenClaw Migration — Transfer Prep"
echo "====================================="
echo ""

# Verify archive exists
if [ ! -f "$ARCHIVE" ]; then
    echo "❌ Archive not found at $ARCHIVE"
    echo "   Run the migration build first."
    exit 1
fi

echo "✅ Archive ready: $ARCHIVE"
echo "   Size: $(ls -lh "$ARCHIVE" | awk '{print $5}')"
echo ""

# Options for transfer
echo "Transfer Options:"
echo ""
echo "1. AirDrop (Mac→Mac):"
echo "   Finder → $ARCHIVE → Share → AirDrop → Brax"
echo ""
echo "2. iCloud/Shared Folder:"
echo "   cp $ARCHIVE ~/Desktop/brax-openclaw-migration.tar.gz"
echo "   # Share via iCloud, Dropbox, Google Drive"
echo ""
echo "3. Direct copy (if on same network/SSH):"
echo "   scp $ARCHIVE brax@his-machine:~/Downloads/"
echo ""
echo "4. USB/physical:"
echo "   cp $ARCHIVE /Volumes/USB/brax-openclaw-migration.tar.gz"
echo ""
echo "════════════════════════════════════════════════════"
echo " WHAT BRAX RECEIVES:"
echo "════════════════════════════════════════════════════"
echo ""
echo "📦 brax-openclaw-migration.tar.gz"
echo "   └── setup.sh                    ← Run this"
echo "   └── README.md                   ← Read this"
echo "   └── workspace-files/            ← 9 core .md files"
echo "   └── skills/                     ← 80 skills"
echo "   └── memory/                     ← 50 daily memory logs"
echo "   └── n8n-workflows/              ← 11 workflow files"
echo "   └── self-improving/             ← Learning system"
echo "   └── data-analysis/              ← Analysis config"
echo ""
echo "════════════════════════════════════════════════════"
echo " BRAX'S SETUP STEPS:"
echo "════════════════════════════════════════════════════"
echo ""
echo "1. Extract:"
echo "   tar -xzf brax-openclaw-migration.tar.gz"
echo "   cd brax-migration"
echo ""
echo "2. Install OpenClaw 2026.3.2:"
echo "   npm install -g openclaw@2026.3.2"
echo ""
echo "3. Run setup:"
echo "   chmod +x setup.sh"
echo "   ./setup.sh"
echo ""
echo "4. Add his Kimi API key:"
echo "   openclaw auth add kimi-coding"
echo ""
echo "5. Add Brave Search key (free):"
echo "   https://api.search.brave.com/app/dashboard"
echo "   # Paste into ~/.openclaw/openclaw.json"
echo ""
echo "6. Start gateway:"
echo "   openclaw gateway start"
echo ""
echo "7. Open webchat:"
echo "   http://localhost:18789"
echo ""
echo "════════════════════════════════════════════════════"
echo ""
echo "✅ Ready to transfer!"
